Add arb loader
aissat/easy_localization_loader pull request #43
Opened 2022-10-21 17:08 UTC by SNNafi

2023-04-22 12:19 UTC, this-is-allan commented
up

2024-05-07 18:07 UTC, SNNafi commented
Any update on this @aissat ?

2024-05-08 07:10 UTC, bw-flagship commented
@SNNafi THere are conflights in this branch

2024-05-13 10:39 UTC, SNNafi commented
@bw-flagship , Fixed merge conflicts

2024-05-13 10:58 UTC, bw-flagship requested changes

2024-05-13 10:58 UTC, bw-flagship commented on README.md
> +supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')],
revert formating

2024-05-13 11:24 UTC, SNNafi commented on README.md
> +supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')],
Reverted

2024-05-13 15:39 UTC, bw-flagship commented
@SNNafi I suppose something went wrong, you have far more changes than before

2024-05-22 21:53 UTC, closed without merging